language: ruby
sudo: false
cache: bundler
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database keg_picker_test;' -U postgres
script:
  - bundle exec rspec
rvm:
  - 2.2.3
notifications:
  email: false
