default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: keg_picker_development

test:
  <<: *default
  database: keg_picker_test

production:
  <<: *default
  database: keg_picker_production
